depends_on:
    - freedesktop-check
    - check-data-files

steps:
    pip_deploy:
        image: python:latest
        commands:
            - pip install twine build PyQt6
            - python -m build
            - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
        secrets: [PYPI_USERNAME, PYPI_PASSWORD]

when:
    event: tag